import "@/styles/globals.css";

import { Inter } from "next/font/google";
import { cookies } from "next/headers";

import { Toaster } from 'sonner';
import { redirect } from "next/navigation";

import { TRPCReactProvider } from "@/trpc/react";
import { getServerAuthSession } from "@/server/auth";



const inter = Inter({
  subsets: ["latin"],
  variable: "--font-sans",
});

export const metadata = {
  title: "Create T3 App",
  description: "Generated by create-t3-app",
  icons: [{ rel: "icon", url: "/favicon.ico" }],
};

// eslint-disable-next-line react/function-component-definition
export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {

  // const session = await getServerAuthSession();
  // if (!session?.user) return redirect("/")

  return (
    <html lang="en">
      <body className={`font-sans ${inter.variable}`}>
        <TRPCReactProvider cookies={cookies().toString()}>
          {children}
        </TRPCReactProvider>
        <Toaster position="top-center" richColors/>
      </body>
    </html>
  );
}
