name: Deploy

on:
  push:
    branches:
      - version-2.0
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Install dependencies
        run: npm i

      - name: Deploy
        env:
          DATABASE_URL: ${{ secrets.DATABASE_URL }}

          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

          NEXTAUTH_URL: ${{secrets.NEXTAUTH_URL}}
          NEXTAUTH_SECRET: ${{ secrets.NEXTAUTH_SECRET}}

          GITHUB_CLIENT_ID: ${{ secrets.GH_ID}}
          GITHUB_CLIENT_SECRET: ${{secrets.GH_SECRET}}
        run: |
          npx prisma generate
          npx sst deploy --stage prod
